package com.bkdwei.model;
// Generated 2016-8-2 7:02:44 by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Classes generated by hbm2java
 */
@Entity
@Table(name = "classes", catalog = "t2")
public class Classes implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -6246257116655981596L;
    private Integer           classId;
    private String            className;
    private Set<Student>      students         = new HashSet<Student>(0);

    public Classes() {
    }

    public Classes(final String className, final Set<Student> students) {
        this.className = className;
        this.students = students;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "classId", unique = true, nullable = false)
    public Integer getClassId() {
        return this.classId;
    }

    @Column(name = "className", length = 50)
    public String getClassName() {
        return this.className;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "classes")
    public Set<Student> getStudents() {
        return this.students;
    }

    public void setClassId(final Integer classId) {
        this.classId = classId;
    }

    public void setClassName(final String className) {
        this.className = className;
    }

    public void setStudents(final Set<Student> students) {
        this.students = students;
    }

}
