package com.bkdwei.model;
// Generated 2016-8-8 18:18:10 by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Classes generated by hbm2java
 */
@Entity
@Table(
        name = "classes", catalog = "t2")
public class Classes implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -1658406972140064338L;
    private Integer           classId;
    private String            className;

    public Classes() {
    }

    public Classes(final String className) {
        this.className = className;
    }

    @Id
    @GeneratedValue(
            strategy = IDENTITY)

    @Column(
            name = "classId", unique = true, nullable = false)
    public Integer getClassId() {
        return classId;
    }

    @Column(
            name = "className", length = 50)
    public String getClassName() {
        return className;
    }

    public void setClassId(final Integer classId) {
        this.classId = classId;
    }

    public void setClassName(final String className) {
        this.className = className;
    }

}
