package com.bkdwei.model;
// Generated 2016-8-8 18:18:10 by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CodeDictionary generated by hbm2java
 */
@Entity
@Table(
        name = "code_dictionary", catalog = "t2")
public class CodeDictionary implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 8957804965103463802L;
    private String            codeId;
    private String            codeName;
    private Integer           id;

    public CodeDictionary() {
    }

    public CodeDictionary(final String codeId, final String codeName) {
        this.codeId = codeId;
        this.codeName = codeName;
    }

    @Column(
            name = "codeId", length = 25)
    public String getCodeId() {
        return codeId;
    }

    @Column(
            name = "codeName", length = 100)
    public String getCodeName() {
        return codeName;
    }

    @Id
    @GeneratedValue(
            strategy = IDENTITY)

    @Column(
            name = "id", unique = true, nullable = false)
    public Integer getId() {
        return id;
    }

    public void setCodeId(final String codeId) {
        this.codeId = codeId;
    }

    public void setCodeName(final String codeName) {
        this.codeName = codeName;
    }

    public void setId(final Integer id) {
        this.id = id;
    }

}
