package com.bkdwei.model;
// Generated 2016-8-8 18:18:10 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Family generated by hbm2java
 */
@Entity
@Table(
        name = "family", catalog = "t2")
public class Family implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 2008334461218078872L;
    private Integer           age;
    private int               id;
    private String            name;
    private String            relationship;
    private String            sex;
    private Student           student;

    public Family() {
    }

    public Family(final int id, final Student student, final String name) {
        this.id = id;
        this.student = student;
        this.name = name;
    }

    public Family(final int id, final Student student, final String name, final Integer age,
            final String sex, final String relationship) {
        this.id = id;
        this.student = student;
        this.name = name;
        this.age = age;
        this.sex = sex;
        this.relationship = relationship;
    }

    @Column(
            name = "age")
    public Integer getAge() {
        return age;
    }

    @Id

    @Column(
            name = "id", unique = true, nullable = false)
    public int getId() {
        return id;
    }

    @Column(
            name = "Name", nullable = false, length = 100)
    public String getName() {
        return name;
    }

    @Column(
            name = "relationship", length = 10)
    public String getRelationship() {
        return relationship;
    }

    @Column(
            name = "sex", length = 4)
    public String getSex() {
        return sex;
    }

    @ManyToOne(
            fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(
            name = "studentId", nullable = false)
    public Student getStudent() {
        return student;
    }

    public void setAge(final Integer age) {
        this.age = age;
    }

    public void setId(final int id) {
        this.id = id;
    }

    public void setName(final String name) {
        this.name = name;
    }

    public void setRelationship(final String relationship) {
        this.relationship = relationship;
    }

    public void setSex(final String sex) {
        this.sex = sex;
    }

    public void setStudent(final Student student) {
        this.student = student;
    }

}
