package com.bkdwei.model;
// Generated 2016-8-8 18:18:10 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * HibernateSequences generated by hbm2java
 */
@Entity
@Table(
        name = "hibernate_sequences", catalog = "t2")
public class HibernateSequences implements java.io.Serializable {

    private HibernateSequencesId id;

    public HibernateSequences() {
    }

    public HibernateSequences(HibernateSequencesId id) {
        this.id = id;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(
            name = "sequenceName", column = @Column(
                    name = "sequence_name")),
            @AttributeOverride(
                    name = "sequenceNextHiValue", column = @Column(
                            name = "sequence_next_hi_value")) })
    public HibernateSequencesId getId() {
        return this.id;
    }

    public void setId(HibernateSequencesId id) {
        this.id = id;
    }

}
