package com.bkdwei.model;
// Generated 2016-8-8 18:18:10 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * IdentificationCard generated by hbm2java
 */
@Entity
@Table(
        name = "identificationCard", catalog = "t2")
public class IdentificationCard implements java.io.Serializable {

    private int    id;
    private String cardNo;

    public IdentificationCard() {
    }

    public IdentificationCard(int id) {
        this.id = id;
    }

    public IdentificationCard(int id, String cardNo) {
        this.id = id;
        this.cardNo = cardNo;
    }

    @Id

    @Column(
            name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(
            name = "cardNo", length = 19)
    public String getCardNo() {
        return this.cardNo;
    }

    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

}
