package com.bkdwei.model;
// Generated 2016-8-2 7:02:44 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * IdentificationCard generated by hbm2java
 */
@Entity
@Table(name = "identificationCard", catalog = "t2")
public class IdentificationCard implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 7931274291467471308L;
    private String            cardNo;
    private int               id;

    public IdentificationCard() {
    }

    public IdentificationCard(final int id) {
        this.id = id;
    }

    public IdentificationCard(final int id, final String cardNo) {
        this.id = id;
        this.cardNo = cardNo;
    }

    @Column(name = "cardNo", length = 19)
    public String getCardNo() {
        return this.cardNo;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setCardNo(final String cardNo) {
        this.cardNo = cardNo;
    }

    public void setId(final int id) {
        this.id = id;
    }

}
