package com.bkdwei.model;
// Generated 2016-8-8 18:18:10 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(
        name = "person", catalog = "t2")
public class Person implements java.io.Serializable {

    private int     id;
    private Integer age;
    private String  name;

    public Person() {
    }

    public Person(int id) {
        this.id = id;
    }

    public Person(int id, Integer age, String name) {
        this.id = id;
        this.age = age;
        this.name = name;
    }

    @Id

    @Column(
            name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(
            name = "age")
    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    @Column(
            name = "name", length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
