package com.bkdwei.model;
// Generated 2016-8-2 7:02:44 by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "t2")
public class Student implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -1137017032364927731L;
    private Classes           classes;
    private Integer           studentId;
    private String            studentName;

    public Student() {
    }

    public Student(final Classes classes, final String studentName) {
        this.classes = classes;
        this.studentName = studentName;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "classId")
    public Classes getClasses() {
        return this.classes;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "studentId", unique = true, nullable = false)
    public Integer getStudentId() {
        return this.studentId;
    }

    @Column(name = "studentName", length = 50)
    public String getStudentName() {
        return this.studentName;
    }

    public void setClasses(final Classes classes) {
        this.classes = classes;
    }

    public void setStudentId(final Integer studentId) {
        this.studentId = studentId;
    }

    public void setStudentName(final String studentName) {
        this.studentName = studentName;
    }

}
