package com.bkdwei.model;
// Generated 2016-8-8 21:54:52 by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(
        name = "student", catalog = "t2", uniqueConstraints = @UniqueConstraint(
                columnNames = { "studentId", "classId" }))
public class Student implements java.io.Serializable {

    private Integer age;
    private Date    birthday;
    private Classes classes;
    private String  hometown;
    private Boolean marital;
    private String  phone;
    private String  sex;
    private Integer studentId;
    private String  studentName;

    public Student() {
    }

    public Student(final Classes classes, final String studentName, final Integer age,
            final String sex, final String hometown, final String phone, final Date birthday,
            final Boolean marital) {
        this.classes = classes;
        this.studentName = studentName;
        this.age = age;
        this.sex = sex;
        this.hometown = hometown;
        this.phone = phone;
        this.birthday = birthday;
        this.marital = marital;
    }

    @Column(
            name = "age")
    public Integer getAge() {
        return age;
    }

    @Temporal(TemporalType.DATE)
    @Column(
            name = "birthday", length = 10)
    public Date getBirthday() {
        return birthday;
    }

    @ManyToOne(
            fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(
            name = "classId")
    public Classes getClasses() {
        return classes;
    }

    @Column(
            name = "hometown", length = 100)
    public String getHometown() {
        return hometown;
    }

    @Column(
            name = "marital")
    public Boolean getMarital() {
        return marital;
    }

    @Column(
            name = "phone", length = 100)
    public String getPhone() {
        return phone;
    }

    @Column(
            name = "sex", length = 10)
    public String getSex() {
        return sex;
    }

    @Id
    @GeneratedValue(
            strategy = IDENTITY)

    @Column(
            name = "studentId", unique = true, nullable = false)
    public Integer getStudentId() {
        return studentId;
    }

    @Column(
            name = "studentName", length = 50)
    public String getStudentName() {
        return studentName;
    }

    public void setAge(final Integer age) {
        this.age = age;
    }

    public void setBirthday(final Date birthday) {
        this.birthday = birthday;
    }

    public void setClasses(final Classes classes) {
        this.classes = classes;
    }

    public void setHometown(final String hometown) {
        this.hometown = hometown;
    }

    public void setMarital(final Boolean marital) {
        this.marital = marital;
    }

    public void setPhone(final String phone) {
        this.phone = phone;
    }

    public void setSex(final String sex) {
        this.sex = sex;
    }

    public void setStudentId(final Integer studentId) {
        this.studentId = studentId;
    }

    public void setStudentName(final String studentName) {
        this.studentName = studentName;
    }

}
