package com.bkdwei.model;
// Generated 2016-8-2 7:02:44 by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "t2")
public class User implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1626851160030298939L;
    private Date              createTime;
    private Integer           id;
    private String            name;
    private String            password;
    private Date              updateTime;

    public User() {
    }

    public User(final String name, final String password, final Date createTime, final Date updateTime) {
        this.name = name;
        this.password = password;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", nullable = true, length = 19)
    public Date getCreateTime() {
        return this.createTime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
        return this.name;
    }

    @Column(name = "password", nullable = false, length = 100)
    public String getPassword() {
        return this.password;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "update_time", nullable = true, length = 19)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setCreateTime(final Date createTime) {
        this.createTime = createTime;
    }

    public void setId(final Integer id) {
        this.id = id;
    }

    public void setName(final String name) {
        this.name = name;
    }

    public void setPassword(final String password) {
        this.password = password;
    }

    public void setUpdateTime(final Date updateTime) {
        this.updateTime = updateTime;
    }

}
